SPURB/participe

package.json
src/App.vue
src/registerServiceWorker.js
src/store.js
src/sw.js
src/views/ConcessaoMartinelli.vue
vue.config.js

Configura update de service worker por ação do usuario. Atualiza conteúdo de concessao-martinelli.
@lordscorp dá uma olhada. Coloquei um build na homologação.

update de SW em app.vue

---

package-lock.json
src/App.vue
src/_consulta.scss
src/components/AntesDepois.vue
src/components/Apoio.vue
src/components/CommentsOption.vue
src/components/Galeria.vue
src/components/MapaOSM.vue
src/components/Modal.vue
src/components/PageTop.vue
src/components/Tabela.vue
src/components/VideoContent.vue
src/components/graf/setor-central-2/infografico.vue
src/components/graf/setor-central-2/pai.vue
src/mixins/consultasCommons.js
src/router.js
src/views/PlanoCicloviario.vue
src/views/SetorCentral2.vue
vue.config.js

Consulta PIU Setor Central. Alterações de componentes: 
Novos:
- AntesDepois
- MapaOsm (plano-cicloviario - #58 )
Alterados:
- Tabela
- Imagem
- Apoio
- Galeria
O linter fez diversas alterações pontuais em outros componentes. A branch `plano-cicloviário` #58   foi mergeada nesta PR. 
Esta branch está publicada em ambiente de homologação:
http://participe.comunicacao.smul.pmsp/

Setor central 2

---

src/_errata.scss
src/views/ConcessaoMartinelli.vue
src/views/SetorCentral2.vue

Inclui errata de concessao-martinelli. Modula 'errata.scss'

---

src/views/SetorCentral2.vue

Adiciona marcador de errata nas imagens (erros 14 e 15), corrige erro id 15

Ajusta erro id 15

---

src/App.vue
src/_errata.scss
src/components/Apoio.vue
src/components/Cabecalho.vue
src/components/Errata.vue
src/components/MenuLateral.vue
src/mixins/consultasCommons.js
src/views/SetorCentral2.vue

Bugs no componente Errata, previne scroll de fora da body, errata PIU Setor Central 2

---

.gitignore
src/components/Indice.vue
src/router.js
src/views/Home.vue
src/views/PoliticaMunicipalTurismo.vue
vue.config.js

Consulta pública da Secretaria de Turismo.

Politica municipal turismo

---

src/router.js
src/views/PlanoDiretorParqueIbirapuera.vue
vue.config.js

Signed-off-by: Renan <renan.smul@gmail.com>

Consulta pdp-ibirapuera (Plano Diretor do Parque Ibirapuera)

---

src/components/AntesDepois.vue
src/components/CommentsContext.vue
src/components/Indice.vue
src/components/PageTop.vue
src/views/Anhembi2.vue
src/views/ArcoPinheiros2.vue
src/views/ConcessaoMartinelli.vue
src/views/GovernoAberto.vue
src/views/Home.vue
src/views/MinutaArcoPinheiros.vue
src/views/ParqueBrigadeiroFariaLima.vue
src/views/ParqueDosEucaliptos.vue
src/views/ParqueJacintoAlberto.vue
src/views/ParqueJardimFelicidade.vue
src/views/ParqueLajeado.vue
src/views/ParqueMinhocao.vue
src/views/PlanoDiretorParqueIbirapuera.vue
src/views/PoliticaMunicipalTurismo.vue
src/views/PortalPrefeitura.vue
src/views/SetorCentral2.vue
src/views/VilaLeopoldina2.vue
src/views/__TEMPLATE_NOVAS_CONSULTAS__.vue

**Resolve #99**
* Cria método (_socialMediaRedirect_) de preenchimento automático das urls de compartilhamento nas redes sociais a partir do objeto "esta_consulta" passado via props para o componente PageTop.
* Retira o objeto "social_assets" das consultas que o passavam para PageTop via props.
___
Alteração em Home e PageTop:
* Se não há nenhuma contribuição numa consulta ativa, "0 contribuições" passa a ser "Nenhuma contribuição até agora". Numa consulta encerrada, "Nenhuma contribuição".
* Se há apenas uma contribuição, fica flexionado no singular ("1 contribuições" » "1 contribuição")

Compartilhamento redes sociais

---

src/components/Apoio.vue
src/components/CommentsContext.vue
src/components/CommentsLoader.vue
src/components/Indice.vue
src/mixins/consultasCommons.js
src/modules/comments.js
src/store.js

Aplicando alterações no fetch das contribuiçoes internas na nova branch

Fetch das contribuicoes em modulo exclusivo na store

---

src/components/Galeria.vue
src/components/Imagem.vue
src/mixins/fallbacks.js
src/views/Home.vue

Lazy loading de imagens e galerias nos componentes `Imagem.vue` e `Galeria.vue` com fallback para ie

Lazy loading em imagens e galerias

---

src/mixins/consultasCommons.js
src/views/ParqueBrigadeiroFariaLima.vue
src/views/ParqueDosEucaliptos.vue
src/views/ParqueJacintoAlberto.vue
src/views/ParqueJardimFelicidade.vue
src/views/ParqueLajeado.vue
src/views/PlanoCicloviario.vue
src/views/PlanoDiretorParqueIbirapuera.vue
src/views/PoliticaMunicipalTurismo.vue
src/views/PremiaSampaEdicao2020.vue
src/views/Tr156.vue
src/views/VidaSegura.vue
tests/e2e/integration/consultas/parque-brigadeiro-faria-lima.spec.js
tests/e2e/integration/consultas/parque-dos-eucaliptos.spec.js
tests/e2e/integration/consultas/parque-jacinto-alberto.spec.js
tests/e2e/integration/consultas/parque-jardim-felicidade.spec.js
tests/e2e/integration/consultas/parque-lajeado.spec.js
tests/e2e/integration/consultas/pdp-ibirapuera.spec.js
tests/e2e/integration/consultas/plano-cicloviario.spec.js
tests/e2e/integration/consultas/politica-municipal-turismo.spec.js
tests/e2e/integration/consultas/premia-sampa-edicao-2020.spec.js
tests/e2e/integration/consultas/tr-156.spec.js
tests/e2e/integration/consultas/vida-segura.spec.js

Inclui método commentId em consultasCommons (DRY). Inclui testes de integracao para estas views alteradas.

Otimiza views e inclui testes de integração

---

src/components/Comments.vue
src/views/JockeyClub.vue

Corrige problema em Comments.vue

---

package-lock.json
package.json
src/components/LayerExplorer.vue
src/components/Pergunta.vue
src/views/MinutaSetorCentral.vue
src/views/Tr156.vue

Corrige mapa 8 da consulta /minuta-piu-setor-central e aplica eslint

---

src/views/Pmadrss.vue

Signed-off-by: Renan <renan.smul@gmail.com>

Introdução final revisada

---

src/components/PageTop.vue

Signed-off-by: Ricardo Henrique Ivanov <X478816@rede.sp>

Adicionado a feature Ver Devolutiva na página PageTop.vue

---

src/views/TrContactCenter.vue

Signed-off-by: Renan <renan.smul@gmail.com>

Corrigidas datas no texto interno.

---

src/components/CommentsLoader.vue
src/store.js
src/views/ConsultaAuto.vue

Ajustes para consulta Concessao Martinelli

Consulta auto

---

src/views/ArcoTiete2.vue

Errata do arco tietê e remoção de css não utilizado.

fix: errata para arco-tiete-2

---

src/store.js

Signed-off-by: Renan <renan.smul@gmail.com>

Ajuste para compatibilidade com json ja codificado para UTF8

---

src/mixins/consultasCommons.js
src/store.js
src/views/__TEMPLATE_NOVAS_CONSULTAS__.vue

completando otimizações decorrentes do ajuste no encoding da api

rewrite: corrige parsing em mutations, otimiza metodos em store e mixins

---

src/components/CommentsOption.vue
src/router.js
src/views/GinasioIbirapuera.vue
vue.config.js

~~Consulta em estágio de homologação. Não mergear~~ .

content(wip): consulta/ibirapuera-pdf

---

package-lock.json
package.json
src/router.bkp.js
src/views/jockey-club-2/JockeyClub2.vue
src/views/jockey-club-2/JockeyClub2Consulta.vue
src/views/jockey-club-2/JockeyClub2Minuta.vue

Ajustes requisitados pela equipe de SPURB

Correções menores
